//임시 데이터라 일단 components에 넣겠습니다..
export interface IMeta {
  pageSize: number;
  totalApplicationsCount: number;
  totalPage: number;
  currentPage: number;
}

export interface IObj {
  [key: string]: any;
}

export interface IData extends IObj {
  id: string;
  name: string;
  phone: string;
  email: string;
  major: string;
  sid: string;
  grade: string;
  enrollmentStatus: string;
  part: string;
  personalInfoAgreementDate: string;
  cvUrl: string;
  firstAnswer: string;
  secondAnswer: string;
  thirdAnswer: string;
  fourthAnswer: string;
  fifthAnswer: string;
  createdDate: string;
  updatedDate: string;
}

export interface IApplicationData {
  meta: IMeta;
  data: IData[];
}

export const FirstApplicationData: IApplicationData = {
  meta: {
    pageSize: 10,
    totalApplicationsCount: 17,
    totalPage: 2,
    currentPage: 1,
  },
  data: [
    {
      id: '1',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '2',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '3',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '4',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '5',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '6',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '7',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '8',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '9',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '10',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
  ],
};

export const SecondApplicationData: IApplicationData = {
  meta: {
    pageSize: 10,
    totalApplicationsCount: 17,
    totalPage: 2,
    currentPage: 1,
  },
  data: [
    {
      id: '11',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '12',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '13',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '14',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '15',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '16',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
    {
      id: '17',
      name: 'choi',
      phone: '01012341234',
      email: 'test@test.com',
      major: '정통',
      sid: '601919',
      grade: '1',
      enrollmentStatus: '재학',
      part: 'web',
      personalInfoAgreementDate: 'some date',
      cvUrl: 'asdf',
      firstAnswer: 'asdf',
      secondAnswer: 'asdf',
      thirdAnswer: 'asdf',
      fourthAnswer: 'asdf',
      fifthAnswer: 'asdf',
      createdDate: 'some date',
      updatedDate: 'some date',
    },
  ],
};
